### ISSUE TITLE
Trigger URL for deployment

### ISSUE THREAD

**Issue by code28** [qutheory/cloud-feedback#1]
I'm actually sure, this is already on the list, but I wanted to be sure, since it would be great to have this feature: An url to trigger a deployment (like in RED).

**Comment by joscdk** [comment]
Yeah actually came to think about this the other days when i implemented auto deploy for the Vapor API docs, so definitely on the list.

Thanks for the suggestion :)

**Comment by joscdk** [comment]
It's now implemented and deployed as discussed in #cloud-2 on Discord
