### ISSUE TITLE
Live logs

### ISSUE THREAD

**Issue by code28** [qutheory/cloud-feedback#2]
A nice feature would be to have "live" logs of the replicas, i.e. when a log is printed, it could appear immediately, so you don't have to reload the logs by closing and re-opening or changing the view options.
Alternative: A dedicated button to refresh the logs, so you don't need to first select a specific pod and then select "all pods" again.

**Comment by joscdk** [comment]
Yes we were actually working on this, however i kept facing issues with the connection from Vapor/NIO websockets to the K8s system, but this is one of the first things (tail/follow log) that is planned to be solved, short after we have stabilized the server setup :)

**Comment by joscdk** [comment]
@code28 live logs is now supported, when you open the Logs Modal, there is a new dropdown, where you can select `Follow`, this will start a live stream linked directly to the container, automatically fetches every new line written :)
